### ISSUE TITLE
secure_domain_lobby_bypass dosn’t work anymore

### ISSUE THREAD

**Issue by Senior-Live** [jitsi-contrib/prosody-plugins#24] opened 2023-09-08 08:23 UTC
I might have found a little bug.
We haven implemented the auto lobby login with secure_domain_lobby_bypass and lobby_autostart
But when I employ this:
//
prejoinConfig: {
enabled: true,
},
//
the autolobby login dosn’t work anymore.
Question: Is this supposed to work like this or is something wrong?

**Comment by Senior-Live** [comment] 2023-09-12 09:41
UPDATE
After update, without prejoinConfig, autolobby dosn't work at all anymore

**Comment by shawnchin** [comment] 2023-09-12 09:59
do you mean secure_domain_lobby_bypass, or lobby_autostart, or both? i.e. does the lobby not automatically start anymore? or that you just cannot bypass the lobby with secure domain auth?

**Comment by Senior-Live** [comment] 2023-09-12 10:57
Can't find email answer, so I'll place it here (too)
Hi Shawn,

Thanks for the reaction.

Using both, lobby starts but dosn't set the password anymore.

**Comment by shawnchin** [comment] 2023-09-12 11:01
ok. so auto lobby works but secure_domain_lobby_bypass doesn't. Will update title to track this issue properly and avoid confusion.

**Comment by shawnchin** [comment] 2023-09-12 11:01
quick question: what do you mean by "but doesn't set the password anymore."?

**Comment by Senior-Live** [comment] 2023-09-12 11:05
Before (with the right configuration) the lobby was automatically 'locked' with as password.
Even de Host needed to enter the password.

**Comment by shawnchin** [comment] 2023-09-12 12:16
I'm sorry, but I'm not sure I understand. lobby_autostarts enables the lobby for all rooms by default but does not set a room password.

Are you referring to the Secure Domain auth (username and password) instead of the room password?

Is the issue that you no longer have the option to authenticate with username+password? Or that a user does not bypass the lobby even though they have successfully authenticated?

**Comment by shawnchin** [comment] 2023-09-12 12:44
Neither of those modules set passwords on the room. 

You either have something else that's setting the room password, or you're referring to Secure Domain auth.

**Comment by Senior-Live** [comment] 2023-09-12 13:11
1-4 Yes, that is correct.
Yes Auth and lobby works ,  but it no longer asks for room password.

**Comment by shawnchin** [comment] 2023-09-12 13:16
Sounds like this really isn't an issue with secure_domain_lobby_bypass or lobby_bypass, but with how room password is handled when Secure Domain and Lobby enabled.

Any ideas @damencho / @emrahcom

**Comment by damencho** [comment] 2023-09-12 13:19
@shawnchin can you give me simple steps to reproduce?

**Comment by Senior-Live** [comment] 2023-09-12 13:20
OK, thanks for understanding.
Wil wait

**Comment by shawnchin** [comment] 2023-09-12 14:28
@Senior-Live I'm afraid I cannot repro your issue. 

This is my setup:
1. Installed latest stable Jitsi Meet (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)
2. Set up Secure Domain (https://jitsi.github.io/handbook/docs/devops-guide/secure-domain/)
3. Enabled secure_domain_lobby_bypass (https://github.com/jitsi-contrib/prosody-plugins/tree/main/secure_domain_lobby_bypass)
4. Enabled lobby_autostart (https://github.com/jitsi-contrib/prosody-plugins/blob/main/lobby_autostart/mod_lobby_autostart.lua)
5. Modified `/usr/share/jitsi-meet/prosody-plugins/mod_lobby_autostart.lua` to automatically set static Room Password based on [this post](https://community.jitsi.org/t/lobby-auto-login/124883/29?u=shawn).
6. Restarted prosody/jicofo/jitsi-videobridge2

The following are my observations, which matches my expectations of how things should work.

### Guest
When they first arrive, if moderator not yet joined, they see this:

![Intermediate_Returns_Drive_Sternly___Jitsi_Meet](https://github.com/jitsi-contrib/prosody-plugins/assets/348157/40c46668-abca-4e6a-a5ca-5f26893dafd8)

Once moderator joins, guest moves into the lobby and sees this:

![Cursor_and_Intermediate_Returns_Drive_Sternly___Jitsi_Meet](https://github.com/jitsi-contrib/prosody-plugins/assets/348157/ba08a085-e088-422e-bf2c-2d18ab378ba1)

The guest has to wait to be admitted, or click on "Enter meeting password" to use the Room Password to enter.

![Cursor_and_Intermediate_Returns_Drive_Sternly___Jitsi_Meet](https://github.com/jitsi-contrib/prosody-plugins/assets/348157/a56ba797-279c-4a10-8356-6eed06c5f8c0)

### Moderator

#### If not yet authenticated

If not yet authenticated, they will first see the "Waiting for Moderator..." dialog as show above. If they click "Log-in", they get the option to authenticate using the username+password set up in Prosody.

![Alksjdhfklajsdf___Jitsi_Meet](https://github.com/jitsi-contrib/prosody-plugins/assets/348157/7b13833e-b27e-412c-b9f7-18ae9f5c6dd6)

On successful auth, they now see the second dialog to enter the Room Password:

![Alksjdhfklajsdf___Jitsi_Meet](https://github.com/jitsi-contrib/prosody-plugins/assets/348157/2af16f1f-4d6d-4d96-973e-b0e5aa9bf745)

They will join they room once they entered the correct password.

#### If previously authenticated

If moderator previously logged in using the same browser, then they no longer see the "Waiting for moderator..." dialog and go straight to the "Password required" dialog.

----

And I see very similar behaviour with prejoinConfig enabled or disabled, except for the extra screen users see before the have to deal with the dialogs.

Does this match your previous or current experience? How is this different from your expected behaviour?

**Comment by shawnchin** [comment] 2023-09-12 15:40
Fells like the issue might be with your setup instead of an issue with latest Jitsi release.

_> But now: Password required is missing / not working._

A few things to try/check:
1. Check `/usr/share/jitsi-meet/prosody-plugins/mod_lobby_autostart.lua` and make sure the changes you made for `set_password` is still there, then restart prosody service and try again.
2. Any errors in prosody logs after you restart prosody?
3. When guest user join, can they use the room password to bypass the lobby?

**Comment by emrahcom** [comment] 2023-09-20 14:55
Fixed in Jitsi `v.8960`

Related topic in the community forum:
https://community.jitsi.org/t/autolobby-login/126670

**Closed by emrahcom** 2023-09-20 14:55 UTC

**Comment by Senior-Live** [comment] 2023-11-07 09:57
Looks like the problem has returned. Anyway it is not working anymore.

**Comment by emrahcom** [comment] 2023-11-07 10:29
I cannot reproduce the same issue on my setup with the latest stable. It works in my case with/without a prejoin page. There may be some configuration issue on your setup.
